trigger:
  batch: true
  branches:
    include:
      - refs/heads/*
  tags:
    include:
      - "TEST-*"
      - "PCC-*"
      - "release-*"
      - "*"

resources:
  repositories:
    - repository: Templates
      type: git
      name: 'TSP DevSecOps/ips-central'
    - repository: Templates-LeanIX
      type: git
      name: 'TSP DevSecOps/leanix-central'

variables:
- template: Library/vars.yaml@Templates
- group: LEANIX

stages:
  - stage: Build_Docker
    # condition: or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), contains(variables['Build.Reason'], 'PullRequest'))
    pool:
      name: LinuxJavaCIBuildAgents
    jobs:
      - job: Builds
        workspace:
          clean: all
        steps:
        - checkout: self
          fetchDepth: 0
        - template: Master.yaml@Templates

  - stage: LeanIX
    pool:
      vmImage: ubuntu-latest
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - job: LeanIX
        steps:
        - checkout: self
        - checkout: Templates-LeanIX
        - template: Master.yaml@Templates-LeanIX