pool:
  name: LocalAgents
  demands:
  - Checkmarx

trigger:
- main
- feature/*
- develop
- dev/*
- release/*
- refs/tags/*

resources:
  repositories:
    - repository: Templates
      type: git
      name: DevSecOps/DevSecOps

schedules:
- cron: 0 21 * * 6
  branches:
    include:
    - main
  always: true
name: $(date:yyyyMMdd)$(rev:.r)

stages:
  - stage:
    pool:
      name: LocalAgents
      demands:
      - Checkmarx
    jobs:
    - job: Phase_1
      displayName: Agent job 1
      timeoutInMinutes: 120
      cancelTimeoutInMinutes: 1

      steps:
      - checkout: self
        clean: true
        fetchDepth: 2

      - task: Checkmarx AST@2
        displayName: CheckmarxOne Scan
        inputs:
          CheckmarxService: 'Checkmarx One - Project - Asset Management'
          projectName: 'ips-application'
          branchName: '$(Build.SourceBranchName)'
