# Generated by Django 4.2.13 on 2024-06-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ips', '0002_choosemyselfdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='choosemyselfdata',
            name='version_number',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
