# Generated by Django 4.2.13 on 2024-07-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ips', '0004_letpmchoosedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='letpmchoosedata',
            name='additional_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
