# Generated by Django 4.2.13 on 2024-07-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ips', '0005_letpmchoosedata_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choosemyselfdata',
            name='strategy',
            field=models.TextField(),
        ),
    ]
